### PR TITLE
Swap logo

### PR DESCRIPTION
**Pull request by tinykite**
## What this does 
This update swaps the old LIL logo, on the homepage, with the current logo. Additionally: 

- Adds an include so that an svg can be rendered inline (without a network request) but not decrease the overall readability of the page html
- Removes an unused id, and swaps it for a classname
- Removes old css specific to the animated gif and replaces it with shallow, basic css for responsive svg sizing

## Notes 
- I noticed that there is some client-side JavaScript that dynamically calculates a height for the container the logo and nav both sit in (in `home.js`). I initially set out to remove it — in favor of using simpler, declarative CSS that would have the additional benefit of responding to changes in window resize or gracefully handle changes in font resizing. But I realized that this is possibly an unnecessary refactor, if we're intending to change nothing else stylistically about the header, and we only need to swap the logo as part of the scope of this work. 

## Screenshots

Side-by-side view of the current homepage, and the updated homepage, at a larger desktop viewport.
Screenshot 2024-02-20 at 5 29 51 PM

Inbetween tablet view of the update homepage, featuring the max size of the logo featured in the [LIL redesign phase 1 Figma mocks](https://www.figma.com/file/PfWjU4OzWP0cGZ8fDlr0CI/LIL-Website-Redesign?type=design&node-id=96%3A2481&mode=design&t=vjCdUdIkMWNVzL9A-1):
Screenshot 2024-02-20 at 5 54 36 PM

Mobile view of the updated homepage
Screenshot 2024-02-20 at 5 55 00 PM

## How to test

I've discovered that the least-error prone way to check out a branch locally is to not follow the instructions github provides on each PR. It feels much more consistent to:

- Add a new remote for my fork of website-static, named meaningfully (for example, named tinykite)
- Run git pull tinykite to make sure you have the latest remote branches
- Run `git checkout swap logo` to checkout this branch

### CODE REVIEW

**Comment by tinykite** [comment]
Moving this to draft to quickly make a fix to better accommodate the footer logo variant, and fix the fill color of the logo

**Review by rebeccacremona — APPROVED** [review]
Looks great!!

Only thoughts: would adding a `title` to the SVG or other alt text-like label be a little clearer than keeping an `.sr-only` span (which is already an improvement over what we had)?

> I noticed that there is some client-side JavaScript that dynamically calculates a height 

Yeah, isn't it a hoot that that's the only JS on this whole site 🤣 ??

Good idea not to address now; that sounds like a perfect thing to tidy at the end if time allows 🙂

**Comment by tinykite** [comment]
> Looks great!!
> 
> Only thoughts: would adding a `title` to the SVG or other alt text-like label be a little clearer than keeping an `.sr-only` span (which is already an improvement over what we had)?
> 
> > I noticed that there is some client-side JavaScript that dynamically calculates a height
> 
> Yeah, isn't it a hoot that that's the only JS on this whole site 🤣 ??
> 
> Good idea not to address now; that sounds like a perfect thing to tidy at the end if time allows 🙂

That's a really great question! I usually avoid adding `title` or `text` content to an inline svg as a general habit, not because it shouldn't ever be done — so thank you for asking! 

I think in the past, I've typically avoided adding a title because: 
- Whether or not it's read aloud can depend on browser and screenreader-specific quirks — including whether or not the svg has other text content, as documented in this [Deque article that tests various patterns for labeling svgs.](https://www.deque.com/blog/creating-accessible-svgs/), which found that many browser/screenreader combinations either ignored the title or ignored the text element's contents when both were present. 
- So frequently, when adding an svg to a page, it's within the context of a link or a button, where it would be recommended to add visually hidden text to label the interactive element rather than label a decorative image. 

I realized this is a situation where I am not familiar with any caveats, so I'd be happy to add it in place of visually hidden text if that's what you'd prefer! Alternatively, I realized — this svg at a minimum should either have a title _or_ it should have an `aria-labelled-by` attribute, to make it clearer that there is a relationship between the text and an image, rather than having text that isn't directly associated with an image or with an interactive element.

**Comment by rebeccacremona** [comment]
Aha! Thanks for that information, all new to me 🙂 !

**Comment by tinykite** [comment]
It's super helpful for me — it's easy for me to not realize I'm doing something because of a habit, not because I absolutely need to! Made a small update for this in [b3c16d4](https://github.com/harvard-lil/website-static/pull/496/commits/b3c16d4c3cee39d7c77e56630a4f952c104200a7)

**Comment by rebeccacremona** [comment]
Love it.

**Pull request merged**
