### PR TITLE
Team edits for about page

### PR DESCRIPTION
**Pull request by abziegler**

### CODE REVIEW

**Comment by rebeccacremona** [comment]
Nice!

This is fine. It's a little sub-optimal to retrieve the list of summer affiliates twice: once in the code you are adding, once in the [include](https://github.com/harvard-lil/website-static/blob/develop/app/_includes/about-people-summer.html). Two strategies for fixing that would be 1) Move all the template code related to the summer affiliates into the include, and use the list generated there; or 2) calculate the list where you do, but then pass it to the include as a variable.

Are you interested in making either of those changes? I'm happy to merge this as-is, and open an issue for one of us to refactor at our convenience.

**Comment by abziegler** [comment]
Wow, you're tough. Respect. I'll fix it.

**Comment by rebeccacremona** [comment]
:-)

**Review by rebeccacremona — COMMENTED** [review]
Looks good to me!

**Pull request merged**
