### PR TITLE
Image compression fix

### PR DESCRIPTION
**Pull request by matteocargnelutti**
The lewis center's picture on /about is currently a ~3MB PNG.

### CODE REVIEW

**Review by bensteinberg — COMMENTED** [review]
Nice. You could also `git rm assets/images/lewis-center-web.png`

**Comment by matteocargnelutti** [comment]
@bensteinberg Indeed!

**Review by bensteinberg — APPROVED** [review]
🤘

**Comment by matteocargnelutti** [comment]
@bensteinberg I just did the same for the other Lewis pic (under /jobs)

**Pull request merged**
