### PR TITLE
Transform: Justice event streaming page

### PR DESCRIPTION
**Pull request by rebeccacremona**
See ENG-659.

Requesting feedback from Clare in Linear.

image

image

image

image

image

### CODE REVIEW

**Review by bensteinberg — APPROVED** [review]

**Comment by bensteinberg** [comment]
Well, "approved" pending tests passing :)

**Comment by rebeccacremona** [comment]
Of _course_ the iframe from IT is invalid HTML.

**Comment by rebeccacremona** [comment]
Okay, I included the original iframe, commented out, in case we need it in some unfathomable emergency: a person could just remove the comment as a hot fix on the server and clear the cloudflare cache and be done.

But because of how iframes work, I don't think there is any chance at all that the tweaks will have changed anything.

**Review by bensteinberg — APPROVED** [review]
Seems fine? Though note that our auto-deployment won't happen if we swap in the original with invalid HTML; we'd have to cause the deployment outside of GH Actions.

**Comment by rebeccacremona** [comment]
Swapped content order per Clare:

image

**Pull request merged**
