### PR TITLE
Add Clare to About Page

### PR DESCRIPTION
**Pull request by clare-stanton**

### CODE REVIEW

**Review by rebeccacremona — CHANGES_REQUESTED** [review]
Congrats on your first pull request! 

This is almost perfect. Just a few tiny tweaks:

1) Do you see that the "key" `clare-stanton` is indented the same number of spaces as the details (image, affiliated, etc.) of JZ's entry? That will make the computer organize your additions as more entries inside JZ's record, rather than making you a record of your own. If you remove the two spaces, so your key is lined up with his, then you'll get your own record!

2) We try to keep this list in alphabetical order, just to be tidy. It doesn't affect anything, but would you mind adding yourself with the other Ss?

3) I'm not sure how the code will work with the bio as > and a return and without a picture (we haven't tried that), but I'll check, and if it doesn't work, we'll figure something else out.

**Comment by rebeccacremona** [comment]
Let me know if you'd like any help making those changes!

**Comment by clare-stanton** [comment]
I believe I put the edits through, thanks for the help! I added a bio, and Andy will take my picture tomorrow. If I'm still missing something let me know.

**Comment by rebeccacremona** [comment]
Perfect! The edits look great. I just tested locally, to see what it looks like without a picture, and unfortunately our website isn't set up to handle that: the grid of people gets all misaligned. Bummer.

So, let's hold off until Andy has your picture ready, and then we can add you in.

**Comment by clare-stanton** [comment]
Bummer, but makes sense - thanks for your help!

**Pull request merged**
